### ISSUE TITLE
No persistency data in dashboards

### ISSUE THREAD

**Issue by worekleszczy** [ScalaConsultants/mesmer-akka-agent#330]
After running `example` project on current [`main`](https://github.com/ScalaConsultants/mesmer-akka-agent/commit/c5abb405f83fe8cf0ebb0cdbe01d76626a4ccefa), generating traffic for `/api/v1/account/UUID/deposit/10.0` endpoint and opening up a grafana dashboard no data is shown on page:
<img width="1562" alt="image" src="https://user-images.githubusercontent.com/11786987/155708054-d8f63cb5-d3ff-46f4-9aa1-3bf7c7e90139.png">

**Comment by lgajowy** [comment]
I've: 
 - removed all my /target directories (to make sure there are no stale jars)
 - run `sbt assembly` 
 
What I noticed is that sbt assembly does not build the otel extension jar. So if you were running from IDE, it was not picked up (it was absent). When I then run `sbt "project example" runWithOtelAgent` it worked.

My guess is that the build.sbt config is not correct since it doesn't assembly the otel agent.

**Comment by lgajowy** [comment]
Looking at this in `build.sbt`:

```
lazy val all = (project in file("."))
  .disablePlugins(sbtassembly.AssemblyPlugin)
  .settings(
    name           := "mesmer-all",
    publish / skip := true
  )
  .aggregate(extension, agent, example, core)
```

There should be otelExtension included in the last line of this snippet.

**Comment by worekleszczy** [comment]
@lgajowy My issue was with `mesmer` agent, but after cleaning everything and running it again everything seems to be ok. I'll close this issue as I can't really reproduce it at this point - if this happens again in the future I'll take another look.
